version: '2.2'
services:
  web:
    image: aspendigital/octobercms
    ports:
      - 8080:80
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql #DB_HOST should match the service name of the database container
      - DB_DATABASE=octobercms
      - DB_USERNAME=$MYSQL_USER
      - DB_PASSWORD=$MYSQL_PASSWORD  
      
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=octobercms
      
  mysqld-metrics-exporter:
    image: prom/mysqld-exporter
    ports:
      - 9104:9104
    environment:
      - DATA_SOURCE_NAME=$$MYSQL_USER:$MYSQL_PASSWORD@(mysql:3306)/
    depends_on:
      - mysql
      
  node_exporter:
    image: prom/node-exporter:latest
    container_name: db1_node_exporter
    ports:
      - "9100:9100"
#    command: --collectors.enabled=diskstats,filesystem,loadavg,meminfo,netdev,stat,time,uname
      
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/config/rules.yml:/etc/prometheus/rules.yml
      - ./prometheus/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
      
  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  blackbox-exporter:
    image: prom/blackbox-exporter
    ports:
      - 9115:9115
    volumes:
      - ./blackbox-exporter/:/config/
    command:
      - '--config.file=/config/blackbox.yml'

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/storage/:/var/lib/grafana
