global:
  scrape_interval: 1m

rule_files:
  - /etc/prometheus/rules.yml

# Alerting specifies settings related to the Alertmanager
alerting:
  alertmanagers:
    - static_configs:
      - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "mysqld-metrics-exporter"
    scrape_interval: 5s
    static_configs:
    - targets: ["mysqld-metrics-exporter:9104"]

  - job_name: "node-exporter"
    scrape_interval: 5s
    static_configs:
    - targets: ["node_exporter:9100"]

  - job_name: 'blackbox-prometheus_test'
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [http_2xx]
      target: [prometheus.io]
    static_configs:
    - targets:
      - blackbox-exporter:9115

  - job_name: 'blackbox' # To get metrics about the exporter itself
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [http_2xx]
      target: [localhost:9115]
    static_configs:
      - targets: 
        - blackbox-exporter:9115

#remote_write:
#  - url: "<Your Prometheus remote_write endpoint>"
#    basic_auth:
#      username: "<Your Grafana Username>"
#      password: "<Your Grafana API key>"